version: "3.8"

services:
  web:
    image: nginx:1.27-alpine
    container_name: whatsapp-only-ecommerce
    restart: unless-stopped
    ports:
      - "19948:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/:/usr/share/nginx/html:ro
